### ISSUE TITLE
Несколько клавиш для аима

### ISSUE THREAD

**Issue by mr-kotik** [Kramar1337/Strinova-AHK-flex#2]
Спасибо за проект, работает отлично, но можно ли как-то сделать что бы можно было назначить несколько клавиш для триггера аима?

**Comment by Kramar1337** [comment]
понял, но не понял. отдельно добавлять такую функцию не буду.
что можно придумать?
делаешь копию папки и там в конфиге другую кнопку ставишь и запускаешь 2 скрипта из разных папок.
повезет и они не будут конфликтовать
